school/school/urls.py
from xml.dom.minidom import Document
from django import views
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (TokenObtainPairView,TokenRefreshView,)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('student_app.urls')),
    path('teacher/',include('teacher_app.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    
] + static(settings.MEDIA_URL, Document_root = settings.MEDIA_ROOT)

school/student_app/urls.py
from django.urls import path
from student_app import views

app_name = "user_app"

urlpatterns = [
    
    path('', views.demo, name='demo'),
    path('student_home/', views.user_home, name='student_home'),
    
    path('login/', views.login_student, name='login_student'),
    path('logout/', views.logout_student, name='logout_student'),

    path('demo_submit/', views.images_submit, name='images_submit'),

    path('add_student/', views.add_student, name='add_student'),



]

school/teacher_app/urls.py
from unicodedata import name
from django.urls import path
from teacher_app import views

app_name = "teacher_app"

urlpatterns = [
    
    path('', views.demo, name='demo'),
    path('teacher_home/', views.teacher_home, name='teacher_home'),

    path('teacher_signup/', views.teacher_signup, name='teacher_signup'),
    path('teacher_logout/', views.admin_logout, name='teacher_logout'),

    path('user_list/', views.UserList.as_view(), name="student_list"),
    path('user_list/<int:pk>', views.UserDetails.as_view(), name="student_details")

    


]

school/student_app/models.py
from distutils.command.upload import upload
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.fields.related import ForeignKey
from django.shortcuts import reverse
from django.core.validators import RegexValidator
from .managers import CustomUserManager
from django.utils.translation import gettext_lazy as _

# Create your models here.




class AuthUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    Mobile_Number = models.CharField(max_length=10, validators=[
                                     RegexValidator(r'^\d{10}$')])
    Address = models.CharField(max_length=200)
    City = models.CharField(max_length=50)
    State = models.CharField(max_length=20)
    bio = models.CharField(max_length=80, null=True, blank=True)
    Pincode = models.CharField(max_length=6, validators=[
        RegexValidator(r'^\d{6}$')])
    image = models.ImageField(upload_to='profile_images', null=True, blank=True)
    is_admin = models.BooleanField(default=False)
    is_user = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []    

    objects = CustomUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.first_name + ' ' + self.last_name

class Demo(models.Model):
    image = models.ImageField(upload_to = 'profile_images', null = True, blank = True)

school/teacher_app/models.py
from django.db import models

# Create your models here.

school/student_app/forms.py
from dataclasses import field
from django import forms
from .models import AuthUser, Demo

class UserloginForm(forms.ModelForm):
    class Meta:
        model = AuthUser
        fields = ('email', 'password', 'image')
        #fields = "__all__"
        # exclude = ('demo', "demo1")
        
        # exclude = ('is_blogger', 'is_useradmin')

class DemoForm(forms.ModelForm):
    class Meta:
        model = Demo
        fields = '__all__'

school/student_app/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login, authenticate, logout
# from django.contrib.auth.models import User

from .models import AuthUser

from .forms import DemoForm, UserloginForm


# Create your views here.

def demo(request):
    return redirect("student_app:login_student")

def user_home(request):
    return render(request, "student_home.html")

def login_student(request):

    if request.method == "POST":

        email = request.POST.get("email")
        password = request.POST.get("password")

        print("u>>>>", email)
        print("p>>>>", password)

        user = authenticate(email=email, password=password)

        print("user>>", user)

        if user is not None and user.is_admin:
            login(request, user)
            return redirect('teacher_app:teacher_home') #Go to admin home
        elif user is not None and user.is_user:
            login(request, user)
            return redirect('student_app:student_home') #Go to user home
        elif user and user.is_superuser:
            return render(request, 'superuser.html') # go to Superuser
            # login(request, user)
            # type_obj = AuthUser.objects.get(email=user)
            # if user.is_authenticated and type_obj.is_user:
            #     return redirect('user_app:user_home') #Go to user home
            # elif user.is_authenticated and type_obj.is_admin:
            #     return redirect('admin_app:admin_home') #Go to admin home
            # elif user.is_authenticated and type_obj.is_superuser:
            #     return render(request, 'superuser.html') # go to Superuser
                    
        #     login(request, user)
        #     return redirect("user_app:user_home")
        # else:
        #     # print("R>>>>>")
        #     return redirect("user_app:login_user")   
    else:   
        return render (request, "login.html")
      
        
        



def logout_student(request):
    logout(request)
    return redirect('student_app:login_student')
    # return render(request, "login_user.html")


def add_student(request):

    if request.method == "POST":
        form_v = UserloginForm(request.POST, request.FILES)
        if form_v.is_valid():
            asd = form_v.save()
            asd.is_user = True
            asd.set_password(asd.password)
            asd.save()
            return redirect("student_app:add_student")
        else:
            print(form_v.errors)

    else: 
        form_v = UserloginForm()
        
    return render (request, "add_student.html", {'form': form_v})

def images_submit(request):
    if request.method == "POST":
        print(request.FILES)
        form = DemoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        else:
            print(form.errors)
    else:
        form = DemoForm()
    return render(request, "demo_submit.html", {"form":form})

school/teacher_app/views.py
from pyexpat import model
from django.shortcuts import render,redirect
from django.contrib.auth import login, authenticate, logout

from student_app.forms import UserloginForm
from django.views.generic import ListView, DetailView
from student_app.models import AuthUser
# from django.contrib.auth.mixins import UserPassesTestMixin,LoginRequiredMixin

# Create your views here.


def demo(request):
    return redirect('teacher_app:teacher_signup')

def teacher_home(request):
    return render(request, "teacher_home.html")

class UserList(ListView):
    model = AuthUser
    template_name = "teacher_app/student_list.html"
    context_object_name = "student_list"    

class UserDetails(DetailView):
    model = AuthUser
    template_name = "teacher_app/student_details.html"
    context_object_name = "user"


# def details(request,id):
#     user = AuthUser.objects.get(id=id)
#     return render(request,'show.html', {'user':user})


def teacher_signup(request):
    if request.method == "POST":
        form_v = UserloginForm(request.POST)
        if form_v.is_valid():
            asd = form_v.save()
            asd.is_admin = True
            asd.set_password(asd.password)
            asd.save()
            return redirect("teacher_app:teacher_signup")
        else:
            print(form_v.errors)
    else: 
        form_v = UserloginForm()
    return render (request, "teacher_signup.html", {'form_v': form_v})


def admin_logout(request):
    logout(request)
    return redirect('student_app:login_student')

school/templates/add_student.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css\style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" charset="utf-8"></script>
    <title>Student Add Page</title>

    <style>
        body{
            background-image: linear-gradient(120deg,#8e44ad,#3498db);
            

        }
    </style>

</head>
<body>
    <!-- <form method="POST">
    User Add
    {% csrf_token %}
        {{ form. }}
    <input type="submit">
</form> -->

<form method="POST" class="login-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form. }}
    <h1>Sign Up</h1>
    
    <div class="txtb">
        <input type="email" name="email">
        <span data-placeholder="email" ></span>
    </div>

    <div class="txtb">
        <input type="password" name="password">
        <span data-placeholder="Password" ></span>
    </div>

    <input type="file" id="img" name="image" accept="image/*" id="id_image">
    <br><br>    

    <!-- <div class="txtb">
        <input type="file" name="image" accept="image/*">
        <span data-placeholder="image" ></span>

    </div> -->

    <input type="submit" class="logbtn" value="Sigh Up">
    
    <div class="bottom-text">
        <a href="{% url 'student_app:student_user' %}"><b>Login</b></a><br><br>
        <a href="{% url 'teacher_app:teacher_signup' %}"><b>SignUp as Teacher</b></a>
    </div>


</form>
<script type="text/javascript">
    $(".txtb input").on("focus",function(){
        $(this).addClass("focus");
    })

    $(".txtb input").on("blur",function(){
        if($(this).val() == "")
        $(this).removeClass("focus");
    })

</script>

</body>
</html>

school/templates/admin_app/student_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{user.email}}
    
</body>
</html>

school/templates/admin_app/student_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>User Details</title>
</head>

<body style="background-color: coral;">
    
    <!-- {% for i in user_list %}
        {{i.email}} <a href="{% url 'admin_app:user_details' i.id %}">Details</a><br>
        
        {% endfor %} -->

      <body>
        <h1>User Details</h1><br>
    
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Email</th>                
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody >
    
            {% for i in user_list %}
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ i.email }}</td>
                <!-- <td>{{ i.EnNumber }}</td>
                <td>{{ i.batch }}</td> -->
                <td>
                    <a class="btn btn-secondary" href="{% url 'admin_app:user_details' i.id %}" role="button">Details</a>
                    
                </td>
              </tr>
            {% endfor %}
    
            </tbody>
          </table>

</body>
</html>

school/templates/demo_submit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Images</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button type = "submit">Submit</button>
</body>
</html>

school/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
        <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}"> -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="icon" type="image/x-icon" href="{% static 'images/blood.png' %}">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" charset="utf-8"></script>

    </head>
    <body>

        <form method="POST" class="login-form">
            {% csrf_token %}
            <h1>Login</h1>
            
            <div class="txtb">
                <input type="email" name="email">
                <span data-placeholder="email" ></span>
            </div>

            <div class="txtb">
                <input type="password" name="password">
                <span data-placeholder="Password" ></span>
            </div>

            <input type="submit" class="logbtn" value="Login">
            
            <div class="bottom-text">
                Don`t have account? <a href="{% url 'student_app:add_student' %}"><b>Sign up</b></a>
            </div>


        </form>
        <script type="text/javascript">
            $(".txtb input").on("focus",function(){
                $(this).addClass("focus");
            })

            $(".txtb input").on("blur",function(){
                if($(this).val() == "")
                $(this).removeClass("focus");
            })
        </script>

      
            
        

    </body>
</html>

school/templates/student_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
</head>
<body>
    {% csrf_token %}
    <h1>Student Home Page</h1>
    <a href="{% url 'student_app:login_student' %}" >Logout</a>
</body>
</html>

school/templates/superuser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Super User</title>
</head>
<body>
    Super User
</body>
</html>

school/templates/teacher_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Home</title>
</head>
<body>
    {% csrf_token %}
    <h1>Teacher Home</h1>
    <a href="{% url 'teacher_app:teacher_logout' %}">Logout</a>
</body>
</html>

school/templates/teacher_signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Teacher SignUp </title>
</head>
<body>
    <!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Animated Login Form</title>
        <link rel="stylesheet" href="{% static 'css\2style.css' %}">
        

    </head>
    <body>
        
        
        <form class="box" method="POST">
            {% csrf_token %}
            {{ form_v. }}
            <h1>Teacher Sign Up</h1>
            <input type="email" name="email" placeholder="Email">
            <input type="password" name="password" placeholder="Password">
            
            <input type="submit" class="logbtn" value="Sigh Up">
            <a href="{% url 'student_app:login_student' %}"><b>Login</b></a>
            


    </body>
</html>
</body>
</html>